<?php

namespace Database\Seeders\iptbm;

use App\Models\iptbm\IptbmProfile;
use Illuminate\Database\Seeder;

class ProfileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $iptbm_profiles = array(
            array('id' => '3', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => '16-S Quiling Sur, City of Batac, Ilocos Norte', 'project_leader' => 'Dionisio S. Bucao', 'manager' => 'Artbellson B. Mamuri', 'year_established' => '2019', 'ip_policy' => '1', 'techno_transfer' => '1', 'logo' => 'public/profile/SWtDNXlgAJdzBm3VVydqXpk1YjjyJNa3SjvYFwVO.png', 'tag_line' => 'Hold High the Green and Gold!', 'created_at' => '2023-08-21 10:15:12', 'updated_at' => '2023-08-30 04:42:01', 'region_id' => '1', 'agency_id' => '1'),
            array('id' => '4', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => NULL, 'project_leader' => NULL, 'manager' => NULL, 'year_established' => NULL, 'ip_policy' => NULL, 'techno_transfer' => NULL, 'logo' => 'public/profile/t6gbsAVftH86MdZOtD1opbLeyF6JJRAHlNWv3S2T.png', 'tag_line' => NULL, 'created_at' => '2023-08-29 23:45:13', 'updated_at' => '2023-08-30 03:44:53', 'region_id' => '8', 'agency_id' => '7'),
            array('id' => '6', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => NULL, 'project_leader' => NULL, 'manager' => 'Dr. Moses B. Appoy', 'year_established' => NULL, 'ip_policy' => NULL, 'techno_transfer' => NULL, 'logo' => 'public/profile/C6s3MP6DXnZm5w32PxJJZ0z1X38Q0bYh6z4zOzD1.jpg', 'tag_line' => NULL, 'created_at' => '2023-08-30 01:05:59', 'updated_at' => '2023-08-30 01:40:42', 'region_id' => '16', 'agency_id' => '15'),
            array('id' => '7', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => NULL, 'project_leader' => NULL, 'manager' => NULL, 'year_established' => NULL, 'ip_policy' => NULL, 'techno_transfer' => NULL, 'logo' => NULL, 'tag_line' => NULL, 'created_at' => '2023-08-30 01:12:06', 'updated_at' => '2023-08-30 01:12:06', 'region_id' => '15', 'agency_id' => '16'),
            array('id' => '8', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => 'Inigo Street, Bo. Obrero, Davao City', 'project_leader' => 'Dr. Evelyn A. Gecale', 'manager' => 'Engr. Filmann T. Simpao', 'year_established' => '2012', 'ip_policy' => '1', 'techno_transfer' => '1', 'logo' => 'public/profile/XZiahPFL5V1pbxa1IwaXYgfTKIPosUF9O5mNzVyw.png', 'tag_line' => NULL, 'created_at' => '2023-08-30 01:19:54', 'updated_at' => '2023-08-30 02:06:13', 'region_id' => '13', 'agency_id' => '21'),
            array('id' => '9', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => 'RDEP Building, University of Rizal System - Morong Campus, Sumulong Street, San Juan, Morong, 1960 Rizal', 'project_leader' => 'Dr. Leo C. Rio', 'manager' => 'Dr. Leo C. Rio', 'year_established' => '2021', 'ip_policy' => '1', 'techno_transfer' => '1', 'logo' => 'public/profile/9gwC4aWEmLFOJr8CzfPaKyq07C7DCBStAXPSYcJf.png', 'tag_line' => '"NURTURING TOMORROW\'S NOBLEST"', 'created_at' => '2023-08-30 01:21:55', 'updated_at' => '2023-08-30 03:11:25', 'region_id' => '5', 'agency_id' => '23'),
            array('id' => '10', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => 'Paseo de Valmayor, Brgy. Timugan, Economic Garden, Los Baños, Laguna', 'project_leader' => 'Noel A. Catibog', 'manager' => 'Noel A. Catibog', 'year_established' => '2016', 'ip_policy' => '1', 'techno_transfer' => '1', 'logo' => 'public/profile/yIm4Xr1kVKC7nqADbOhhlj0sIKc2j8t2GeYeAQ5C.jpg', 'tag_line' => 'GALING PCAARRD', 'created_at' => '2023-08-30 01:23:55', 'updated_at' => '2023-08-30 03:59:12', 'region_id' => '5', 'agency_id' => '14'),
            array('id' => '11', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => NULL, 'project_leader' => NULL, 'manager' => NULL, 'year_established' => NULL, 'ip_policy' => NULL, 'techno_transfer' => NULL, 'logo' => 'public/profile/P8FQ8qQfjKeZ3RHL9y6QOAp0tBtv1Z4Nq0V8737j.jpg', 'tag_line' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Scelerisque felis imperdiet proin fermentum leo vel orci porta. ', 'created_at' => '2023-08-30 01:25:37', 'updated_at' => '2023-08-30 03:45:23', 'region_id' => '8', 'agency_id' => '18'),
            array('id' => '12', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => NULL, 'project_leader' => NULL, 'manager' => NULL, 'year_established' => NULL, 'ip_policy' => NULL, 'techno_transfer' => NULL, 'logo' => NULL, 'tag_line' => NULL, 'created_at' => '2023-08-30 01:39:45', 'updated_at' => '2023-08-30 01:39:45', 'region_id' => '1', 'agency_id' => '2'),
            array('id' => '13', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => '1st Floor, Interdisciplinary Research Building, Cavite State University, Indang, Cavite', 'project_leader' => 'Teddy F. Tepora', 'manager' => 'Teddy F. Tepora', 'year_established' => NULL, 'ip_policy' => '1', 'techno_transfer' => NULL, 'logo' => 'public/profile/fWi6TghTjjTrgpbgGurEahBCevkAUwzP3Dp9aSV3.jpg', 'tag_line' => NULL, 'created_at' => '2023-08-30 01:41:03', 'updated_at' => '2023-08-30 04:32:01', 'region_id' => '5', 'agency_id' => '19'),
            array('id' => '14', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => 'CorCAARRD', 'project_leader' => NULL, 'manager' => NULL, 'year_established' => NULL, 'ip_policy' => NULL, 'techno_transfer' => NULL, 'logo' => NULL, 'tag_line' => NULL, 'created_at' => '2023-08-30 01:44:38', 'updated_at' => '2023-08-30 05:14:22', 'region_id' => '16', 'agency_id' => '25'),
            array('id' => '15', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => NULL, 'project_leader' => NULL, 'manager' => NULL, 'year_established' => NULL, 'ip_policy' => NULL, 'techno_transfer' => NULL, 'logo' => NULL, 'tag_line' => NULL, 'created_at' => '2023-08-30 01:45:41', 'updated_at' => '2023-08-30 01:45:41', 'region_id' => '6', 'agency_id' => '30'),
            array('id' => '16', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => 'Research Management Services-Knowledge and Technology Transfer Management (RMS-KTTM) Office, 2nd floor SSC-II Bldg., BatStateU The NEU, Rizal Avenue Ext., Batangas City 4200, Philippines', 'project_leader' => 'Dr. Leandro A. Dalhag', 'manager' => 'Dr. Leandro A. Dalhag', 'year_established' => '2021', 'ip_policy' => '1', 'techno_transfer' => '1', 'logo' => 'public/profile/6CkNkHbFmINyBTY5ZGxFJkP7O0x1WtbqcedUyRNi.jpg', 'tag_line' => 'Leading Innovations, Transforming Lives, Building the Nation', 'created_at' => '2023-08-30 01:51:06', 'updated_at' => '2023-08-30 06:08:05', 'region_id' => '5', 'agency_id' => '20'),
            array('id' => '17', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => NULL, 'project_leader' => NULL, 'manager' => NULL, 'year_established' => NULL, 'ip_policy' => NULL, 'techno_transfer' => NULL, 'logo' => NULL, 'tag_line' => NULL, 'created_at' => '2023-08-30 01:52:02', 'updated_at' => '2023-08-30 01:52:02', 'region_id' => '8', 'agency_id' => '22'),
            array('id' => '18', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => NULL, 'project_leader' => NULL, 'manager' => NULL, 'year_established' => NULL, 'ip_policy' => NULL, 'techno_transfer' => NULL, 'logo' => NULL, 'tag_line' => NULL, 'created_at' => '2023-08-30 01:59:10', 'updated_at' => '2023-08-30 01:59:10', 'region_id' => '6', 'agency_id' => '33'),
            array('id' => '19', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => NULL, 'project_leader' => NULL, 'manager' => NULL, 'year_established' => NULL, 'ip_policy' => NULL, 'techno_transfer' => NULL, 'logo' => NULL, 'tag_line' => NULL, 'created_at' => '2023-08-30 02:06:20', 'updated_at' => '2023-08-30 02:06:20', 'region_id' => '15', 'agency_id' => '34'),
            array('id' => '20', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => 'Brgy. Kulapi, Lucban, Quezon', 'project_leader' => 'Dr. Nona D. Nagares', 'manager' => NULL, 'year_established' => NULL, 'ip_policy' => '1', 'techno_transfer' => NULL, 'logo' => 'public/profile/quarwjmDSABaMDKAoezu8mgzvJ61x2kbdOGZwKN9.png', 'tag_line' => NULL, 'created_at' => '2023-08-30 02:08:00', 'updated_at' => '2023-08-30 04:50:24', 'region_id' => '5', 'agency_id' => '35'),
            array('id' => '21', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => NULL, 'project_leader' => NULL, 'manager' => NULL, 'year_established' => NULL, 'ip_policy' => NULL, 'techno_transfer' => NULL, 'logo' => NULL, 'tag_line' => NULL, 'created_at' => '2023-08-30 02:09:25', 'updated_at' => '2023-08-30 02:09:25', 'region_id' => '6', 'agency_id' => '36'),
            array('id' => '22', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => 'BU Guinobatan Compound, Morera, Guinobatan, Albay', 'project_leader' => 'Christopher O. Pacardo', 'manager' => NULL, 'year_established' => '2022', 'ip_policy' => '1', 'techno_transfer' => '1', 'logo' => 'public/profile/vnCi5TNq2fQyOwjpdNlGR378JTiuI33ZQjdZ9dSV.jpg', 'tag_line' => '#LetsContinueToRAISEBicol', 'created_at' => '2023-08-30 03:21:33', 'updated_at' => '2023-09-04 23:49:36', 'region_id' => '7', 'agency_id' => '31'),
            array('id' => '23', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => 'Visayas State University, RDE Hall Visca, Baybay City Leyte', 'project_leader' => 'Dr. Maria Juliet C. Ceniza', 'manager' => NULL, 'year_established' => NULL, 'ip_policy' => '1', 'techno_transfer' => '1', 'logo' => 'public/profile/smrjMWks7tkYRqcunYrl0D5GJvUepLcDmbLTbE7P.png', 'tag_line' => NULL, 'created_at' => '2023-08-30 03:36:08', 'updated_at' => '2023-08-30 06:58:06', 'region_id' => '10', 'agency_id' => '37'),
            array('id' => '24', 'rrdc_chair' => NULL, 'consortium_dir' => NULL, 'office_address' => NULL, 'project_leader' => NULL, 'manager' => NULL, 'year_established' => NULL, 'ip_policy' => NULL, 'techno_transfer' => NULL, 'logo' => NULL, 'tag_line' => NULL, 'created_at' => '2023-08-30 05:41:23', 'updated_at' => '2023-08-30 05:41:23', 'region_id' => '13', 'agency_id' => '38')
        );

        foreach ($iptbm_profiles as $profile) {
            IptbmProfile::create($profile);
        }

    }
}
