<?php

namespace Database\Seeders\iptbm;

use App\Models\iptbm\IptbmTechnologyProfile;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TechnologySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {


        $iptbm_technology_profiles = array(
            array('id' => '3', 'iptbm_profile_id' => '4', 'title' => 'Calamansi Juice Extractor', 'year_developed' => '2019', 'tech_desc' => 'The present invention relates to a juice extractor for citrus crops, specifically Calamansi (Citrofortunella microcarpa). It was reported that when Calamansi (Citrofortunella microcarpa) juice is machine-extracted, the seeds are crushed together thus making the juice bitter. This invention offers to meet the certain limitations of the existing machines for Calamansi juice extraction. The machine has a suitable perforating and juice extraction assemblies for efficient production of quality juice for commercial scale processing. It has high extraction efficiency which can be attributed to suitable design based on the characteristics of the Calamansi. The juice were efficiently extracted by perforating the fruits prior to the compressive action of the rotating screw conveyor against the stationary perforated drum.', 'tech_photo' => 'public/technology_profiles/QCA0TqYeddGxzrgbCFS8dIEN9h7ahFZ4eObQjwVI.jpg', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-29 23:59:54', 'updated_at' => '2023-08-29 23:59:54'),
            array('id' => '4', 'iptbm_profile_id' => '4', 'title' => 'Twining Machine', 'year_developed' => '2012', 'tech_desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'tech_photo' => 'public/technology_profiles/pnAkOtSlvLcFRxtOjymzUGKc6zEUpsJ7Qm8F0qM9.jpg', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 00:09:22', 'updated_at' => '2023-08-30 00:09:22'),
            array('id' => '5', 'iptbm_profile_id' => '3', 'title' => 'Portable Boga', 'year_developed' => '2022', 'tech_desc' => '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."', 'tech_photo' => 'public/technology_profiles/wJcdPXSMMwk8yhBEfNR3LrvF4kH0J9lToWNc8l3B.jpg', 'tech_owner' => '4', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 01:08:12', 'updated_at' => '2023-08-30 01:08:12'),
            array('id' => '6', 'iptbm_profile_id' => '6', 'title' => 'A Composition of Citron Lemon Peanut Marmalade', 'year_developed' => '2023', 'tech_desc' => 'A Citron Lemon Peanut Marmalade comprising the following component: gathering, washing and peeling citron lemon fruits and peanut of good quality; separating the rind with the pulp and slicing the rind into small cubes; soaking the rind for 6-8 hours; draining the thin syrup; adding water extract; mixing 250 grams pulp extract and 125 grams sugar; bring the mixture into boil; adding the rind into the mixture and cooking it until  it reaches thick consistency; adding roasted ground peanut; skimming off scums from the mixture; and pouring the mixture in a sterilized jar.', 'tech_photo' => 'public/technology_profiles/DOORJlP38uowOsIKhqHu5W1JojhHSakIm7OJFW61.jpg', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 01:31:06', 'updated_at' => '2023-08-30 01:37:02'),
            array('id' => '7', 'iptbm_profile_id' => '3', 'title' => 'Portable Vulcanizer', 'year_developed' => '2019', 'tech_desc' => 'The portable vulcanizing device is designed with a vulcanizing base having associated structures such as a locking structure, Vulcanizer arm and heating element 5 circuit that cooperatively and communicably engage to each other. The Vulcanizer assembly is operated with 220 volts. If inner tube is then to vulcanize, patch is then placed covering the punctured part and place the inner tube to the heater plate with paper or foil to protect the tube, using the lever arm press until lever arm is lock by the interlock mechanism, swivel the switch to on position indicator lights on, wait until the 10 indicator lights go off, and wait for ten minutes to cool the inner tube, on luck the lever arm to remove inner tube. Check the inner tube by inflating and submerge it in water to check for possible air leak, return interior to exterior and inflate the tire at 30 Psi.', 'tech_photo' => 'public/technology_profiles/XlvBZfA3yxsfpQO3CvmbCyQj6GKOmLsd1DCXNZS8.png', 'tech_owner' => '5', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 02:50:04', 'updated_at' => '2023-08-30 02:50:04'),
            array('id' => '8', 'iptbm_profile_id' => '8', 'title' => 'Mechanical Coconut Climber', 'year_developed' => '2022', 'tech_desc' => 'The Mechanical Coconut Climber is a promising innovation developed by the College of Agriculture and Related Sciences of the University of Southeastern
Philippines. Augmented from the existing Coconut Climbing Device in India, the Mechanical Coconut Climber relieves the ill-suited functions of the Indian-made
Climber to the Philippines\' coconut characteristics, which makes climbing coconut trees more accessible to Filipinos. Moreover, it aids the declining number of
coconut harvesters due to the high risk of accidents during climbing and the increasing number of aging farmers.', 'tech_photo' => 'public/technology_profiles/pYBriYbns3jyVZLui5KqNuLGolBKAt1KjQZGtZhz.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 03:36:10', 'updated_at' => '2023-08-30 03:36:10'),
            array('id' => '9', 'iptbm_profile_id' => '11', 'title' => 'A Process of Synthesizing Hydroxyapatite from Scallop Shells', 'year_developed' => '2023', 'tech_desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'tech_photo' => 'public/technology_profiles/bNQUsJNahIlIozJxlP63H8OoFsemZGVOa6gWh55F.jpg', 'tech_owner' => '3', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 03:36:45', 'updated_at' => '2023-08-30 03:36:45'),
            array('id' => '10', 'iptbm_profile_id' => '20', 'title' => 'Nipa Sugar', 'year_developed' => '2021', 'tech_desc' => 'The utility model is related to food processing, specifically, developing standard process for alternative nipa palm sweetener (sugar). The method of sugar production from nipa is comprised of: collecting sap at a set time during crop season of nipa; sorting, filtering and weighing of sap; boiling of sap; coagulating the boiled sap; crystallizing the coagulated sap to obtain a nipa sugar; drying the nipa sugar; and storing of the dried nipa sugar, wherein the boiling is done by using a combination of a double jacketed kettle and biomass operated kettle.', 'tech_photo' => 'public/technology_profiles/uZduLMi4l1LRUwkkLiSjV1O1PxT0I8iHFT9bhjn5.jpg', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 03:36:52', 'updated_at' => '2023-08-30 03:36:52'),
            array('id' => '11', 'iptbm_profile_id' => '22', 'title' => 'Defibering Machine', 'year_developed' => '2019', 'tech_desc' => 'A machine for extracting fibers of different fiber crop commodities such as pineapple, abaca, and banana.', 'tech_photo' => 'public/technology_profiles/tyLNgvz1tE5Tv5bLftz53xhMxtoIcfYsJOistelP.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 03:37:23', 'updated_at' => '2023-08-30 03:37:23'),
            array('id' => '12', 'iptbm_profile_id' => '22', 'title' => 'BAMBOO VENEER SCRAPING MACHINE', 'year_developed' => '2019', 'tech_desc' => 'Veneers are offspring of bamboo processing technology. These are thin sheets of bamboo that are glued together to form panels, either by hot or cold pressing, conditioned for  3 days and laminated before they are converted into decorative floor tiles, table tops and panels. However, the use of bamboo veneers is currently not familiar in the region. Additionally, the existing machine is not locally accessible to farmers. Since the use of bamboo as veneer is promising, there is a need for an efficient, highly-productive, cost-effective and environmentally friendly bamboo scraping machine to boost the productivity and contribute to the growing industry of bamboo processing.', 'tech_photo' => 'public/technology_profiles/QpgnDahyHj2VeFa5LGXzdKqCsHKIHYMSqbWnl0MQ.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 03:43:21', 'updated_at' => '2023-08-30 03:43:21'),
            array('id' => '14', 'iptbm_profile_id' => '13', 'title' => 'ASMA Low-cost Smoking Technology
', 'year_developed' => '2019', 'tech_desc' => ':  ASMA is an automated smoked fish technology which integrates the operations of a smoking chamber and a biomass-fired smoke generator through a computer-based system. It is designed and fabricated for village-level smoked fish processing. The main objective in designing and fabricating the machine is to assist local processors in producing better quality smoked fish products by controlling smoking temperature, relative humidity, and smoking time during processing.', 'tech_photo' => 'public/technology_profiles/0epNSdOMhdGQZmW4L9pY6m4fD6umABJ90D14Av4y.png', 'tech_owner' => '3', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 03:45:44', 'updated_at' => '2023-08-30 03:45:44'),
            array('id' => '15', 'iptbm_profile_id' => '9', 'title' => 'SWITCHING LOGIC TRAINER BOARD', 'year_developed' => '2001', 'tech_desc' => 'The main objective of this present utility model is to formulate a low cost but
effective trainer board in switching logic that all educational training
institutions along electrical motor controls, industrial circuit process, design
and controls and electrical engineering can use in the training and
preparation of their respective students.', 'tech_photo' => 'public/technology_profiles/tE5wEuBZ1gTxNwpV6opDGC2FCxuxzG1JoNqFV1rV.jpg', 'tech_owner' => '5', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 03:47:59', 'updated_at' => '2023-08-30 03:47:59'),
            array('id' => '16', 'iptbm_profile_id' => '11', 'title' => 'A Method of Producing Hydroxyapatite from Fish Bones', 'year_developed' => '2022', 'tech_desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc aliquet bibendum enim facilisis. Ut venenatis tellus in metus vulputate eu scelerisque felis. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Justo nec ultrices dui sapien eget mi proin. Faucibus a pellentesque sit amet. Amet nisl suscipit adipiscing bibendum est. Vulputate ut pharetra sit amet aliquam. Tortor posuere ac ut consequat semper. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Molestie a iaculis at erat pellentesque adipiscing. Proin nibh nisl condimentum id venenatis a condimentum. Nunc aliquet bibendum enim facilisis gravida. At risus viverra adipiscing at in.', 'tech_photo' => 'public/technology_profiles/5MfnyYP2OTo0w241vNgXiMoeJT1D2wJQwsuTbs7Z.jpg', 'tech_owner' => '3', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 03:50:51', 'updated_at' => '2023-08-30 03:50:51'),
            array('id' => '17', 'iptbm_profile_id' => '13', 'title' => 'HYPOD: Hybrid Powered Multi Commodity Dryer', 'year_developed' => '2020', 'tech_desc' => 'The invention relates to a hybrid-powered multi-commodity dryer equipped with a wind-powered ventilator that helps in the moisture removal process of agriculture and marine products for safe product storage and increased product shelf-life.
The invention can be used both during dry and wet seasons. In dry weather conditions, the invention can benefit from ambient air and solar energy to effect moisture removal. Meanwhile, during wet conditions, an external heat source embodied in a biomass furnace for example can be tapped on the airflow inlet system to channel heat to the drying air.', 'tech_photo' => 'public/technology_profiles/fAE1PmrhWzHR1NN7fIyfXbPcbFe9uSVDrYn2NzOX.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 03:56:42', 'updated_at' => '2023-08-30 03:56:42'),
            array('id' => '18', 'iptbm_profile_id' => '23', 'title' => 'Abaca Stripping Machine', 'year_developed' => '2001', 'tech_desc' => 'This machine is used for for abaca', 'tech_photo' => 'public/technology_profiles/OMep5AjIMbQS1xnZdUq7wHkHbaAcNWdlh6SwRLpo.jpg', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 03:58:35', 'updated_at' => '2023-08-30 03:58:35'),
            array('id' => '19', 'iptbm_profile_id' => '10', 'title' => 'Itik PINAS', 'year_developed' => '2016', 'tech_desc' => 'Itik Pinas is a genetically superior breeder duck which has a higher average productive period of 70% in a year, compared with 55% for the old breed. The strains of Itik Pinas are products of organized breeding and selection that focus on the uniformity of physical characteristics, higher and predictable egg production performance, and consistent egg quality.', 'tech_photo' => 'public/technology_profiles/j7j5JIqNdnhW8GdhirRUhYwtRz0ycf9eUUR2dD7J.jpg', 'tech_owner' => '2', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 03:58:54', 'updated_at' => '2023-08-30 03:58:54'),
            array('id' => '20', 'iptbm_profile_id' => '23', 'title' => 'Method of Producing Yuca Puff from
Cassava Grates', 'year_developed' => '2021', 'tech_desc' => 'Yuca puffs are composed of rehydrated cassava grates, vegetable oil, and salt which are then processed into the extruder. The Yuca puffs were cut into bite pieces and baked at a certain time. ', 'tech_photo' => 'public/technology_profiles/QLsctOFhmimVpIqGmG0oClCjCZ9C72lbr99Z01cD.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 03:59:38', 'updated_at' => '2023-08-30 03:59:38'),
            array('id' => '21', 'iptbm_profile_id' => '3', 'title' => 'Multi-fuel Dryer', 'year_developed' => '2017', 'tech_desc' => 'The multi-fuel dryer is a versatile equipment that uses various fuels such as LPG, electricity, and combustible materials like wood, charcoal, and agricultural waste. It is designed for drying purposes and can also function as an oven. This single device can utilize different fuel sources simultaneously or individually to generate heat. The heat circulates through convection within the combustion chamber\'s walls, allowing it to dry fish, fruits, grains, clothes, and even bake foods. It offers a two-in-one feature, serving as both a drying device and an oven, capable of handling different products in separate chambers simultaneously.', 'tech_photo' => 'public/technology_profiles/XT9GQXEu6oIComDLhkSEvTSq7rON6fdhDBvWYnmW.jpg', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 04:01:20', 'updated_at' => '2023-08-30 04:01:20'),
            array('id' => '22', 'iptbm_profile_id' => '11', 'title' => 'A Process of Producing Honey-Calamansi Flavored Ginger Gel Using Liquid Pectin', 'year_developed' => '2021', 'tech_desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Quis auctor elit sed vulputate mi sit amet. Nulla facilisi nullam vehicula ipsum a. Vel eros donec ac odio tempor orci dapibus ultrices. Facilisi etiam dignissim diam quis enim. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Mus mauris vitae ultricies leo integer malesuada. Netus et malesuada fames ac turpis egestas integer eget. Ultricies lacus sed turpis tincidunt id. ', 'tech_photo' => 'public/technology_profiles/iAG0aKjLcIL0uicoEJpQQ6s3FBZEFVJWeimxCUvw.jpg', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 04:04:11', 'updated_at' => '2023-08-30 04:04:11'),
            array('id' => '23', 'iptbm_profile_id' => '22', 'title' => 'Separator Machine', 'year_developed' => '2018', 'tech_desc' => 'With the consumers becoming more aware of the nutritional deficiencies in white rice, some have begun to rethink their diet and replaced white rice with brown rice.  Unlike white rice, brown rice does not go through the process of milling and polishing and hence retains its immense treasure of healthful components. The resulting product is a mixture of brown rice and paddy mixture which is not marketable, thus a paddy separator is needed to be added to the rice milling systems in order to segregate the paddy from the brown rice. At present, the available paddy separators design in the market require large space area and are quite costly for small scale millers. Hence, the design and fabrication of a low cost paddy separator that requires a small space area.', 'tech_photo' => 'public/technology_profiles/lOrlGcNDKM5bpx9CZZ1GQ9hjX5yzAINtDV93TSM4.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 04:04:32', 'updated_at' => '2023-08-30 04:04:32'),
            array('id' => '24', 'iptbm_profile_id' => '6', 'title' => 'A Process of Making Wine from Medinilla Magnifica Leaves', 'year_developed' => '2016', 'tech_desc' => 'The process of making medinilla magnifica wine involves several steps. Initially, the leaves are gathered, cleaned, and weighed (500g). These leaves are boiled with 5 liters of water for 20-30 minutes, then strained. Brown sugar (100 mg per 4 cups of liquid) is added and dissolved through simmering. After cooling to lukewarm, dry yeast (7.5 ml per 4 cups) is incorporated. The mixture ferments for a month under cloth cover. Pasteurization follows (25 mins at 80°C) before cooling, sediment settling, and siphoning into sealed bottles, resulting in the final wine.', 'tech_photo' => 'public/technology_profiles/MQbsz60QOZGb4vPvSGaKW4EleGEsCPMZjBxKY3Cm.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 04:23:56', 'updated_at' => '2023-08-30 04:23:56'),
            array('id' => '25', 'iptbm_profile_id' => '22', 'title' => 'Pili Size Sorting Machine', 'year_developed' => '2022', 'tech_desc' => 'Designed to sort the pili in small, medium, and large sizes. Fourth discharge unit is designed for pili nuts which did not conform to the available sizing standard of the machine.', 'tech_photo' => 'public/technology_profiles/aHqUi4K5Y2sBHGWU2jXTy1wu7J0U9qhY7GJ7dsmR.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 04:24:44', 'updated_at' => '2023-08-30 04:24:44'),
            array('id' => '26', 'iptbm_profile_id' => '11', 'title' => 'A Process of Producing Liquid Pectin from Pectin-Containing Agricultural Wastes', 'year_developed' => '2022', 'tech_desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Quis auctor elit sed vulputate mi sit amet. Nulla facilisi nullam vehicula ipsum a. Vel eros donec ac odio tempor orci dapibus ultrices. Facilisi etiam dignissim diam quis enim. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Mus mauris vitae ultricies leo integer malesuada. Netus et malesuada fames ac turpis egestas integer eget. Ultricies lacus sed turpis tincidunt id. ', 'tech_photo' => 'public/technology_profiles/cPsioltUbVV7S57wKMTPMWAaGXjX2j9UyI6GBDP0.jpg', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 04:32:07', 'updated_at' => '2023-08-30 04:32:07'),
            array('id' => '27', 'iptbm_profile_id' => '10', 'title' => 'LAMP Kit for Swine Diseases', 'year_developed' => '2020', 'tech_desc' => 'LAMP Kit for Swine Diseases', 'tech_photo' => 'public/technology_profiles/yjoJFjGvlV6zs6Mr08pUXbL4AubnjVQ4acGHakpr.jpg', 'tech_owner' => '2', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 04:38:28', 'updated_at' => '2023-08-30 04:38:28'),
            array('id' => '28', 'iptbm_profile_id' => '13', 'title' => 'Tugi Syrup', 'year_developed' => '2022', 'tech_desc' => 'Low Glycemic Index Alternative sweetener made from locally harvested lesser yam or Dioscorea Esculenta', 'tech_photo' => 'public/technology_profiles/aXt0xEr5DmRcjPTZ1dAmGbLgnqOcpE83GePNjQmC.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 05:06:18', 'updated_at' => '2023-08-30 05:06:18'),
            array('id' => '29', 'iptbm_profile_id' => '22', 'title' => 'Organic-Based Animal Feed Pellets', 'year_developed' => '2019', 'tech_desc' => 'Agricultural processing generates a lot of agricultural wastes which are generally left unutilized, are becoming a threat to global health and food security. It is in this premise that the inventors would like to address the use of waste materials that have immense potential and are readily available in the locality as feed ingredients in pelleting animal feeds. Hence, the formulation of organic-based animal feeds using varying proportions of azolla, madre de agua, coconut pressed cake, and pili pulp with two levels of molasses. The formulation of the organic animal feed pellets, comprises 45-55% azolla, 25-35% madre de agua, 3-10% coconut meal, 3-10% pili pulp, and 7-15% molasses. ', 'tech_photo' => 'public/technology_profiles/6n4mD7Qycsj9wuHRLhwvHAfZ0PAuRKldygFWNXAk.png', 'tech_owner' => '2', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 05:39:44', 'updated_at' => '2023-08-30 05:41:06'),
            array('id' => '30', 'iptbm_profile_id' => '22', 'title' => 'Malunggay Deleafing Machine', 'year_developed' => '2019', 'tech_desc' => 'There are numerous malunggay-based products available in the market today. The leaf powder is mainly used for food fortification as ingredient of bread, noodles, juices, milk, and tea, while the leaf powered capsule is mostly used as food supplement and herbal medicine since the leaves are loaded with various nutrients like vitamins and minerals. In spite of growing Moringa industry, there is still shortage of good quality moringa leaves as raw material, there are gaps that needs to be addressed like upgrading of various postharvest processing of moringa such as deleafing. At present, the usual removal of malunggay leaves is commonly done manually, which takes almost 4-6 hours to deleaf 10 kg of leaves. Hence, the design and fabrication of malunggay deleafing machine.', 'tech_photo' => 'public/technology_profiles/ozVMdUZFGYfSruXy1hTtWWxtSEepI8Jo1qhxl1C1.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 05:46:16', 'updated_at' => '2023-08-30 05:46:16'),
            array('id' => '31', 'iptbm_profile_id' => '22', 'title' => 'Energy-Generating Pedal-Operated Foxtail Millet Thresher', 'year_developed' => '2018', 'tech_desc' => 'Millet is a very promising alternative crop for rice to address rice shortage and malnutrition that the country is facing with its amazing nutrition content and health benefits. In spite of all these extraordinary qualities and capacities of millet, the area under millet production has been shrinking over the last decades because of the difficult post-harvest processes it undergoes before it can be consumed for food. Threshing operation are done manually by either beating action or foot trampling. Hence, the design and fabrication of an energy-generating pedal-operated foxtail millet thresher to improve the traditional threshing operation of the crop.', 'tech_photo' => 'public/technology_profiles/RmgBJBEsFt1MTWHIJnv7f2AXn2HK3JzLNlbARViQ.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 05:48:24', 'updated_at' => '2023-08-30 05:48:24'),
            array('id' => '32', 'iptbm_profile_id' => '22', 'title' => 'Millet Hulling Machine', 'year_developed' => '2018', 'tech_desc' => 'As mentioned previously, Millet is a promising alternative for rice because of its nutrient content and health benefits. However, threshing as well as milling are laborious and time-consuming as it is still being done manually. Traditional milling of millet is done by hand pounding the grains in a mortar and pestle. To address this problem, researchers (students and faculty) from BU Guinobatan (formerly BUCAF), designed and fabricated a millet hulling machine.', 'tech_photo' => 'public/technology_profiles/k7NcgnU6zRyLWvKA0SL37dhO1xiUKdIUrl4MMMR0.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 05:49:18', 'updated_at' => '2023-08-30 05:49:18'),
            array('id' => '33', 'iptbm_profile_id' => '22', 'title' => 'Multifiber Crop Stripping and Pressing Machine', 'year_developed' => '2018', 'tech_desc' => 'Buri and karagumoi are two of the indigenous materials that the government can consider to meet the increasing demand of the fiber industry. Like abaca, these materials produce high quality fibers which are essential in making good quality crafts. However, the preparation of the materials for weaving is laborious and time-consuming. Hence, the design and fabrication of the Multi-Fiber Crop Stripping and Pressing Machine. This machine does not only minimize the time and ease of the work of the craft makers, but also improve the quality of buri and karagumoi strips that will be used in producing quality crafts with the machine stripping efficiency of 75% and machine pressing efficiency of 71%, respectively.', 'tech_photo' => 'public/technology_profiles/pSDMzfu6OtoYiddi47iW6BluH2aSRrTIpOEyNCGO.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 05:50:17', 'updated_at' => '2023-08-30 05:50:17'),
            array('id' => '34', 'iptbm_profile_id' => '22', 'title' => 'Abaca Cutting and Carding Machine', 'year_developed' => '2019', 'tech_desc' => 'The abaca fiber has vast potentials for different industrial uses due to its strength and long fibers and one of it is the use of abaca fiber for the production of sinamay. Making sinamay is a long process. Although existing abaca fiber machine separates the abaca fibers faster compared to traditional (manual) method, the person using the machine experiences a difficulty in feeding the abaca fibers to the machine and the process of separating the fibers in the machine is processed 2-3 times to separate the fibers well. The said process result to a less efficient production, low quality product, and is dangerous. To overcome these problems, researchers designed and fabricated an abaca cutting and carding machine.', 'tech_photo' => 'public/technology_profiles/KpxluDu9C3KdG6dxVAuBVowGOUKLG450Qsxk7Q0w.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 05:51:08', 'updated_at' => '2023-08-30 05:51:08'),
            array('id' => '35', 'iptbm_profile_id' => '22', 'title' => 'Pulverizing and Moulding Machine', 'year_developed' => '2019', 'tech_desc' => 'Department of Science and Technology (DOST) has identified muscovado in the 2005-2010 Philippine Export Development Plan as one of the priority export products due to increasing demand of this health sugar in the European Union and in Japan. However, most of muscovado manufacturers have yet to pass the strict requirements of the international market. To improve the marketability of muscovado sugar and meet the increasing demand for muscovado-based products, the quality and appearance must be improved. Hence, the design and fabrication of the pulverizing and moulding machine.', 'tech_photo' => 'public/technology_profiles/I74EDnDUjADXiD0dhTLoPS5sKWxFZleLrDrrd9rS.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 05:52:48', 'updated_at' => '2023-08-30 05:52:48'),
            array('id' => '36', 'iptbm_profile_id' => '22', 'title' => 'Multifiber Crop Slitter Presser', 'year_developed' => '2022', 'tech_desc' => 'This Multifiber slitter presser is a modification of Multi-fiber crop striping and pressing machine, previously designed by undergraduate students and faculty as part of their thesis study. As shown in the figure, the design is more compact making easy to transport, especially to remote areas, where karagumoi and buri plantation is usually located. It has undergone Techno Demonstration activities at Bulusan, Sorsogon participated by the Women’s Association. Moreover, this technology has been applied to DOST to fund its pre-commercialization activities.', 'tech_photo' => 'public/technology_profiles/bPuHIlQaB73xvNt8ZyPuDJuKmPQpyHF0t58zzy3u.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 05:55:05', 'updated_at' => '2023-08-30 05:55:05'),
            array('id' => '37', 'iptbm_profile_id' => '22', 'title' => 'Pili Testa Remover with Integrated Steamer', 'year_developed' => '2022', 'tech_desc' => 'Pili Testa Remover with Integrated Steamer', 'tech_photo' => 'public/technology_profiles/jTizB6eVuVG5B7YDMdsZr8Py9yQSGPMwOYxeysGz.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 06:04:44', 'updated_at' => '2023-08-30 06:04:44'),
            array('id' => '38', 'iptbm_profile_id' => '22', 'title' => 'Pili Oil Extractor', 'year_developed' => '2022', 'tech_desc' => 'Pili Oil Extractor with Integrated Filter System', 'tech_photo' => 'public/technology_profiles/xnFad64U1T3vfNHloZ57Jo29OGgiUBeqvI639k58.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 06:14:42', 'updated_at' => '2023-08-30 06:14:42'),
            array('id' => '39', 'iptbm_profile_id' => '22', 'title' => 'Pili Depulping Machine', 'year_developed' => '2022', 'tech_desc' => 'Pili Depulping Machine With Adjustable Rollers', 'tech_photo' => 'public/technology_profiles/CYajLjuhgtPbhnSp9PxI7Qoo6SHGYgTvXFOq9PpI.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 06:15:12', 'updated_at' => '2023-08-30 06:15:12'),
            array('id' => '40', 'iptbm_profile_id' => '22', 'title' => 'Pili Nut Cracker ', 'year_developed' => '2022', 'tech_desc' => 'Pili Nut Cracker With Multiple Adjustable Blade Assembly', 'tech_photo' => 'public/technology_profiles/KpmqhsYmYcFGEeg3FNAaaOOwBEUVhSLmA4guvwFa.png', 'tech_owner' => '1', 'tech_research_proj' => NULL, 'tech_agency_res_donor' => NULL, 'tech_res_amount' => NULL, 'tech_trans_plan' => NULL, 'created_at' => '2023-08-30 06:15:37', 'updated_at' => '2023-08-30 06:15:37')
        );

        foreach ($iptbm_technology_profiles as $tech)
        {
            IptbmTechnologyProfile::create($tech);
        }

    }
}
